services:
  qvideo:
    image: qvideo:test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env/env.local
    volumes:
      - ./src/main/resources/secret.jwk:/work/secret.jwk:ro